package com.manjano.bus.models

// Complete country list
object CountryRepository {
    val countries = listOf(
        Country("🇰🇪", "+254", "Kenya", "KE"), // Default
        Country("🇦🇫", "+93", "Afghanistan", "AF"),
        Country("🇦🇱", "+355", "Albania", "AL"),
        Country("🇩🇿", "+213", "Algeria", "DZ"),
        Country("🇦🇸", "+1684", "American Samoa", "AS"),
        Country("🇦🇩", "+376", "Andorra", "AD"),
        Country("🇦🇴", "+244", "Angola", "AO"),
        Country("🇦🇮", "+1264", "Anguilla", "AI"),
        Country("🇦🇬", "+1268", "Antigua and Barbuda", "AG"),
        Country("🇦🇷", "+54", "Argentina", "AR"),
        Country("🇦🇲", "+374", "Armenia", "AM"),
        Country("🇦🇼", "+297", "Aruba", "AW"),
        Country("🇦🇺", "+61", "Australia", "AU"),
        Country("🇦🇹", "+43", "Austria", "AT"),
        Country("🇦🇿", "+994", "Azerbaijan", "AZ"),
        Country("🇧🇸", "+1242", "Bahamas", "BS"),
        Country("🇧🇭", "+973", "Bahrain", "BH"),
        Country("🇧🇩", "+880", "Bangladesh", "BD"),
        Country("🇧🇧", "+1246", "Barbados", "BB"),
        Country("🇧🇾", "+375", "Belarus", "BY"),
        Country("🇧🇪", "+32", "Belgium", "BE"),
        Country("🇧🇿", "+501", "Belize", "BZ"),
        Country("🇧🇯", "+229", "Benin", "BJ"),
        Country("🇧🇲", "+1441", "Bermuda", "BM"),
        Country("🇧🇹", "+975", "Bhutan", "BT"),
        Country("🇧🇴", "+591", "Bolivia", "BO"),
        Country("🇧🇦", "+387", "Bosnia and Herzegovina", "BA"),
        Country("🇧🇼", "+267", "Botswana", "BW"),
        Country("🇧🇷", "+55", "Brazil", "BR"),
        Country("🇮🇴", "+246", "British Indian Ocean Territory", "IO"),
        Country("🇻🇬", "+1284", "British Virgin Islands", "VG"),
        Country("🇧🇳", "+673", "Brunei", "BN"),
        Country("🇧🇬", "+359", "Bulgaria", "BG"),
        Country("🇧🇫", "+226", "Burkina Faso", "BF"),
        Country("🇧🇮", "+257", "Burundi", "BI"),
        Country("🇰🇭", "+855", "Cambodia", "KH"),
        Country("🇨🇲", "+237", "Cameroon", "CM"),
        Country("🇨🇦", "+1", "Canada", "CA"),
        Country("🇨🇻", "+238", "Cape Verde", "CV"),
        Country("🇧🇶", "+599", "Caribbean Netherlands", "BQ"),
        Country("🇰🇾", "+1345", "Cayman Islands", "KY"),
        Country("🇨🇫", "+236", "Central African Republic", "CF"),
        Country("🇹🇩", "+235", "Chad", "TD"),
        Country("🇨🇱", "+56", "Chile", "CL"),
        Country("🇨🇳", "+86", "China", "CN"),
        Country("🇨🇽", "+61", "Christmas Island", "CX"),
        Country("🇨🇨", "+61", "Cocos (Keeling) Islands", "CC"),
        Country("🇨🇴", "+57", "Colombia", "CO"),
        Country("🇰🇲", "+269", "Comoros", "KM"),
        Country("🇨🇬", "+242", "Congo - Brazzaville", "CG"),
        Country("🇨🇩", "+243", "Congo - Kinshasa", "CD"),
        Country("🇨🇷", "+506", "Costa Rica", "CR"),
        Country("🇭🇷", "+385", "Croatia", "HR"),
        Country("🇨🇺", "+53", "Cuba", "CU"),
        Country("🇨🇾", "+357", "Cyprus", "CY"),
        Country("🇨🇿", "+420", "Czechia", "CZ"),
        Country("🇩🇰", "+45", "Denmark", "DK"),
        Country("🇩🇯", "+253", "Djibouti", "DJ"),
        Country("🇩🇲", "+1767", "Dominica", "DM"),
        Country("🇩🇴", "+1809", "Dominican Republic", "DO"),
        Country("🇪🇨", "+593", "Ecuador", "EC"),
        Country("🇪🇬", "+20", "Egypt", "EG"),
        Country("🇸🇻", "+503", "El Salvador", "SV"),
        Country("🇬🇶", "+240", "Equatorial Guinea", "GQ"),
        Country("🇪🇷", "+291", "Eritrea", "ER"),
        Country("🇪🇪", "+372", "Estonia", "EE"),
        Country("🇸🇿", "+268", "Eswatini", "SZ"),
        Country("🇪🇹", "+251", "Ethiopia", "ET"),
        Country("🇫🇯", "+679", "Fiji", "FJ"),
        Country("🇫🇮", "+358", "Finland", "FI"),
        Country("🇫🇷", "+33", "France", "FR"),
        Country("🇬🇦", "+241", "Gabon", "GA"),
        Country("🇬🇲", "+220", "Gambia", "GM"),
        Country("🇬🇪", "+995", "Georgia", "GE"),
        Country("🇩🇪", "+49", "Germany", "DE"),
        Country("🇬🇭", "+233", "Ghana", "GH"),
        Country("🇬🇷", "+30", "Greece", "GR"),
        Country("🇬🇩", "+1473", "Grenada", "GD"),
        Country("🇬🇹", "+502", "Guatemala", "GT"),
        Country("🇬🇳", "+224", "Guinea", "GN"),
        Country("🇬🇼", "+245", "Guinea-Bissau", "GW"),
        Country("🇬🇾", "+592", "Guyana", "GY"),
        Country("🇭🇹", "+509", "Haiti", "HT"),
        Country("🇭🇳", "+504", "Honduras", "HN"),
        Country("🇭🇺", "+36", "Hungary", "HU"),
        Country("🇮🇸", "+354", "Iceland", "IS"),
        Country("🇮🇳", "+91", "India", "IN"),
        Country("🇮🇩", "+62", "Indonesia", "ID"),
        Country("🇮🇷", "+98", "Iran", "IR"),
        Country("🇮🇶", "+964", "Iraq", "IQ"),
        Country("🇮🇪", "+353", "Ireland", "IE"),
        Country("🇮🇱", "+972", "Israel", "IL"),
        Country("🇮🇹", "+39", "Italy", "IT"),
        Country("🇨🇮", "+225", "Ivory Coast", "CI"),
        Country("🇯🇲", "+1876", "Jamaica", "JM"),
        Country("🇯🇵", "+81", "Japan", "JP"),
        Country("🇯🇴", "+962", "Jordan", "JO"),
        Country("🇰🇿", "+7", "Kazakhstan", "KZ"),
        Country("🇰🇪", "+254", "Kenya", "KE"),
        Country("🇰🇮", "+686", "Kiribati", "KI"),
        Country("🇽🇰", "+383", "Kosovo", "XK"),
        Country("🇰🇼", "+965", "Kuwait", "KW"),
        Country("🇰🇬", "+996", "Kyrgyzstan", "KG"),
        Country("🇱🇦", "+856", "Laos", "LA"),
        Country("🇱🇻", "+371", "Latvia", "LV"),
        Country("🇱🇧", "+961", "Lebanon", "LB"),
        Country("🇱🇸", "+266", "Lesotho", "LS"),
        Country("🇱🇷", "+231", "Liberia", "LR"),
        Country("🇱🇾", "+218", "Libya", "LY"),
        Country("🇱🇮", "+423", "Liechtenstein", "LI"),
        Country("🇱🇹", "+370", "Lithuania", "LT"),
        Country("🇱🇺", "+352", "Luxembourg", "LU"),
        Country("🇲🇬", "+261", "Madagascar", "MG"),
        Country("🇲🇼", "+265", "Malawi", "MW"),
        Country("🇲🇾", "+60", "Malaysia", "MY"),
        Country("🇲🇻", "+960", "Maldives", "MV"),
        Country("🇲🇱", "+223", "Mali", "ML"),
        Country("🇲🇹", "+356", "Malta", "MT"),
        Country("🇲🇭", "+692", "Marshall Islands", "MH"),
        Country("🇲🇷", "+222", "Mauritania", "MR"),
        Country("🇲🇺", "+230", "Mauritius", "MU"),
        Country("🇲🇽", "+52", "Mexico", "MX"),
        Country("🇫🇲", "+691", "Micronesia", "FM"),
        Country("🇲🇩", "+373", "Moldova", "MD"),
        Country("🇲🇨", "+377", "Monaco", "MC"),
        Country("🇲🇳", "+976", "Mongolia", "MN"),
        Country("🇲🇪", "+382", "Montenegro", "ME"),
        Country("🇲🇸", "+1664", "Montserrat", "MS"),
        Country("🇲🇦", "+212", "Morocco", "MA"),
        Country("🇲🇿", "+258", "Mozambique", "MZ"),
        Country("🇲🇲", "+95", "Myanmar", "MM"),
        Country("🇳🇦", "+264", "Namibia", "NA"),
        Country("🇳🇷", "+674", "Nauru", "NR"),
        Country("🇳🇵", "+977", "Nepal", "NP"),
        Country("🇳🇱", "+31", "Netherlands", "NL"),
        Country("🇳🇨", "+687", "New Caledonia", "NC"),
        Country("🇳🇿", "+64", "New Zealand", "NZ"),
        Country("🇳🇮", "+505", "Nicaragua", "NI"),
        Country("🇳🇪", "+227", "Niger", "NE"),
        Country("🇳🇬", "+234", "Nigeria", "NG"),
        Country("🇳🇺", "+683", "Niue", "NU"),
        Country("🇰🇵", "+850", "North Korea", "KP"),
        Country("🇲🇰", "+389", "North Macedonia", "MK"),
        Country("🇳🇴", "+47", "Norway", "NO"),
        Country("🇴🇲", "+968", "Oman", "OM"),
        Country("🇵🇰", "+92", "Pakistan", "PK"),
        Country("🇵🇼", "+680", "Palau", "PW"),
        Country("🇵🇸", "+970", "Palestine", "PS"),
        Country("🇵🇦", "+507", "Panama", "PA"),
        Country("🇵🇬", "+675", "Papua New Guinea", "PG"),
        Country("🇵🇾", "+595", "Paraguay", "PY"),
        Country("🇵🇪", "+51", "Peru", "PE"),
        Country("🇵🇭", "+63", "Philippines", "PH"),
        Country("🇵🇱", "+48", "Poland", "PL"),
        Country("🇵🇹", "+351", "Portugal", "PT"),
        Country("🇵🇷", "+1787", "Puerto Rico", "PR"),
        Country("🇶🇦", "+974", "Qatar", "QA"),
        Country("🇷🇴", "+40", "Romania", "RO"),
        Country("🇷🇺", "+7", "Russia", "RU"),
        Country("🇷🇼", "+250", "Rwanda", "RW"),
        Country("🇼🇸", "+685", "Samoa", "WS"),
        Country("🇸🇲", "+378", "San Marino", "SM"),
        Country("🇸🇹", "+239", "São Tomé and Príncipe", "ST"),
        Country("🇸🇦", "+966", "Saudi Arabia", "SA"),
        Country("🇸🇳", "+221", "Senegal", "SN"),
        Country("🇷🇸", "+381", "Serbia", "RS"),
        Country("🇸🇨", "+248", "Seychelles", "SC"),
        Country("🇸🇱", "+232", "Sierra Leone", "SL"),
        Country("🇸🇬", "+65", "Singapore", "SG"),
        Country("🇸🇰", "+421", "Slovakia", "SK"),
        Country("🇸🇮", "+386", "Slovenia", "SI"),
        Country("🇸🇧", "+677", "Solomon Islands", "SB"),
        Country("🇸🇴", "+252", "Somalia", "SO"),
        Country("🇿🇦", "+27", "South Africa", "ZA"),
        Country("🇰🇷", "+82", "South Korea", "KR"),
        Country("🇸🇸", "+211", "South Sudan", "SS"),
        Country("🇪🇸", "+34", "Spain", "ES"),
        Country("🇱🇰", "+94", "Sri Lanka", "LK"),
        Country("🇸🇩", "+249", "Sudan", "SD"),
        Country("🇸🇷", "+597", "Suriname", "SR"),
        Country("🇸🇪", "+46", "Sweden", "SE"),
        Country("🇨🇭", "+41", "Switzerland", "CH"),
        Country("🇸🇾", "+963", "Syria", "SY"),
        Country("🇹🇼", "+886", "Taiwan", "TW"),
        Country("🇹🇯", "+992", "Tajikistan", "TJ"),
        Country("🇹🇿", "+255", "Tanzania", "TZ"),
        Country("🇹🇭", "+66", "Thailand", "TH"),
        Country("🇹🇱", "+670", "Timor-Leste", "TL"),
        Country("🇹🇬", "+228", "Togo", "TG"),
        Country("🇹🇴", "+676", "Tonga", "TO"),
        Country("🇹🇹", "+1868", "Trinidad and Tobago", "TT"),
        Country("🇹🇳", "+216", "Tunisia", "TN"),
        Country("🇹🇷", "+90", "Turkey", "TR"),
        Country("🇹🇲", "+993", "Turkmenistan", "TM"),
        Country("🇹🇨", "+1649", "Turks and Caicos Islands", "TC"),
        Country("🇹🇻", "+688", "Tuvalu", "TV"),
        Country("🇺🇬", "+256", "Uganda", "UG"),
        Country("🇺🇦", "+380", "Ukraine", "UA"),
        Country("🇦🇪", "+971", "United Arab Emirates", "AE"),
        Country("🇬🇧", "+44", "United Kingdom", "GB"),
        Country("🇺🇸", "+1", "United States", "US"),
        Country("🇺🇾", "+598", "Uruguay", "UY"),
        Country("🇺🇿", "+998", "Uzbekistan", "UZ"),
        Country("🇻🇺", "+678", "Vanuatu", "VU"),
        Country("🇻🇦", "+379", "Vatican City", "VA"),
        Country("🇻🇪", "+58", "Venezuela", "VE"),
        Country("🇻🇳", "+84", "Vietnam", "VN"),
        Country("🇾🇪", "+967", "Yemen", "YE"),
        Country("🇿🇲", "+260", "Zambia", "ZM"),
        Country("🇿🇼", "+263", "Zimbabwe", "ZW")
)
    fun getDefaultCountry(): Country = countries.first()
}
